[[session]]
name = "dot"
path = "~/dotfiles"

[[session]]
name = "explore"
path = "~/dev/explore"

[[session]]
name = "iamb"
path = "~/"
startup_command = "iamb"

[[session]]
name = "spotify"
path = "~/"
startup_command = "ncspot"

[default_session]
preview_command = "eza --all --git --icons --color=always {}"
